### ISSUE TITLE
default.dic不生效

### ISSUE THREAD

**Issue by wrqvince** [NLPchina/elasticsearch-analysis-ansj#114]
ansj.cfg.yml里是这么配置的：
```
# 全局变量配置方式一
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  dic: default.dic 
```

ES启动日志也显示加载成功了：
[2018-04-18T17:36:03,359][INFO ][o.a.d.i.File2Stream      ] path to stream default.dic
[2018-04-18T17:36:03,935][INFO ][o.a.l.DicLibrary         ] load dic use time:576 path is : default.dic
[2018-04-18T17:36:04,219][INFO ][o.a.l.DATDictionary      ] init core library ok use time : 277
[2018-04-18T17:36:04,520][INFO ][o.a.l.NgramLibrary       ] init ngram ok use time :265
[2018-04-18T17:36:04,523][INFO ][ansj-initializer         ] init ansj plugin ok , goodluck youyou

但是实际运行不生效：
我自己加了一行 b2    n    2，然后在kibana测试
GET _analyze 
{
  "analyzer":"query_ansj",
  "text":"维生素b2片"
}
加过分出 维生素 b 2片，而不是我想要的 维生素 b2 片

更可气的是，default里原有得分词也没生效。
