### ISSUE TITLE
怎么在插件中加载自己训练的crf模型

### ISSUE THREAD

**Issue by TeriMoni** [NLPchina/elasticsearch-analysis-ansj#202]

**Comment by shi-yuan** [comment]
直接配置crf文件地址即可：

```yml
ansj:
  # http,file,jar,class,jdbc 都支持
  crf: jar://crf.model
```

https://github.com/NLPchina/elasticsearch-analysis-ansj#242%E6%88%96520%E4%BB%A5%E4%B8%8A
