### ISSUE TITLE
如何在elasticsearch.yml 中配置用户自定义词典的路径

### ISSUE THREAD

**Issue by fqhaier** [NLPchina/elasticsearch-analysis-ansj#21]
如何在elasticsearch.yml 中配置用户自定义词典的路径
请大侠给个例子

**Comment by ansjsun** [comment]
````
## ansj配置
ansj:
 dic_path: "ansj/dic/user/" ##用户词典位置
 ambiguity_path: "ansj/dic/ambiguity.dic" ##歧义词典
 enable_name_recognition: true ##人名识别
 enable_num_recognition: true ##数字识别
 enable_quantifier_recognition: false ##量词识别
 enabled_stop_filter: true ##是否基于词典过滤
 stop_path: "ansj/dic/stopLibrary.dic" ##停止过滤词典

````

首页..说明文档中有的..ctrl+f : 分词文件配置
