### ISSUE TITLE
es8.8.2配置分词不生效

### ISSUE THREAD

**Issue by 1056442479** [NLPchina/elasticsearch-analysis-ansj#229]
**配置文件信息：**
```
 ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  #dic: default.dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
  # http方式加载
  dic_d1: http://xxxx:9000/words-hot-refresh/keyword.dic
  # jar中文件加载
  #dic_d2: jar://org.ansj.dic.DicReader|/dic2.dic
  # 从数据库中加载
  #dic_d3: jdbc://jdbc:mysql://xxxx:3306/ttt?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|username|password|select name as name,nature,freq from dic where type=1
  # 从自定义类中加载,YourClas  extends PathToStream
  #dic_d3: class://xxx.xxx.YourClas|ohterparam

  #过滤词典配置
  #stop: http,file,jar,class,jdbc 都支持
  stop_key1: http://xxxxxx:9000/words-hot-refresh/extra_stopword.txt
```
## 3、使用GET /_cat/ansj/config 获取的配置信息如下
```
{
  "ambiguity": [],
  "dic_d1": "http://xxx:9000/words-hot-refresh/keyword.dic",
  "stop": [
    "stop_key1"
  ],
  "synonyms": [
    "synonyms_key1"
  ],
  "crf": [
    "crf"
  ],
  "stop_key1": "http://xxx:9000/words-hot-refresh/extra_stopword.txt",
  "isQuantifierRecognition": "true",
  "isRealName": "false",
  "isNumRecognition": "true",
  "isNameRecognition": "true",
  "synonyms_key1": "http://xxxx:9000/words-hot-refresh/synonym.txt",
  "dic": [
    "dic_d1",
    "dic"
  ]
}
```
## 4、GET /_cat/ansj?text=收养登记&type=index_ansj 分词后的结果是
```
{
  "result": [
    {
      "name": "收养",
      "nature": "v",
      "offe": 0,
      "realName": "收养",
      "synonyms": null
    },
    {
      "name": "登记",
      "nature": "v",
      "offe": 2,
      "realName": "登记",
      "synonyms": null
    }
  ]
}
```
应该是
```
{
  "result": [
    {
      "name": "收养登记",
      "nature": "v",
      "offe": 0,
      "realName": "收养登记",
      "synonyms": null
    }
  ]
}
```
能看下哪里有问题吗？
