### ISSUE TITLE
求救：elasticsearch2.3.x版本配置文件elasticsearch.yml怎么配置redis 啊？

### ISSUE THREAD

**Issue by wyxabd** [NLPchina/elasticsearch-analysis-ansj#23]
我是按作者文档来配置，但启动es时，一直报：没有找到redis相关配置!
说明一下：我是前启动redis再启动es的，并且都是在同一台服务器上，没有网络问题。
求高手帮忙解答，谢谢！！！

**Comment by shi-yuan** [comment]
```
ansj:
 redis:
  pool:
   maxactive: 20
   maxidle: 10
   maxwait: 100
   testonborrow: true
  ip: 127.0.0.1:6379
  channel: ansj_term ## publish时的channel名称
  write:
    dic: "ext.dic" ##如果有使用redis的pubsub方式更新词典，默认使用 这个目录是相对于dic_path
```
