### ISSUE TITLE
ansj elasticsearch插件停词问题

### ISSUE THREAD

**Issue by wpzdm** [NLPchina/elasticsearch-analysis-ansj#25]
日志显示停词库加成功，但是分词结果中仍然有停词，求助！
我试过每行一个单词，以及如下这样
```
与    p    1000
专业    n    1000
```
两种停词库格式
es版本2.3.3

**Comment by shi-yuan** [comment]
ansj配置：
## ansj配置
```
ansj:
  dic_path: "ansj/dic/user/" ##用户词典位置
  ambiguity_path: "ansj/dic/ambiguity.dic" ##歧义词典
  enable_name_recognition: true ##人名识别
  enable_num_recognition: true ##数字识别
  enable_quantifier_recognition: false ##量词识别
  enabled_stop_filter: true ##是否基于词典过滤
  stop_path: "ansj/dic/stopLibrary.dic" ##停止过滤词典
```
stopLibrary.dic的内容：
```
与
专业

```
测试 http://127.0.0.1:9200/_cat/test/analyze?text=我与小明的专业是计算机&analyzer=dic_ansj ：
```
我  		      0		 1 		0 		r 		
小明 		    2	 	4 		1 		nz		
的  		      4		 5 		2		 uj		
是  		      7		 8 		3		 v 		
计算机		 8		 11		 4		 n 	
```
没问题的。

你可以重新install一下，之前有过更新
