### ISSUE TITLE
可否对某个索引禁用停词？

### ISSUE THREAD

**Issue by wpzdm** [NLPchina/elasticsearch-analysis-ansj#41]
比如通过类似下面这样的配置？
```
PUT /my_index
{
   "settings":{
      "analysis":{
         "analyzer":{
            "default":{
            	"type": "search_ansj",
            	"enabled_stop_filter": false
            }
         }
      }
   }
}
```

**Comment by shi-yuan** [comment]
目前配置是全局的，暂时不支持！

不过，配置这块，后期会修改，支持这种自定义的：[#40](https://github.com/NLPchina/elasticsearch-analysis-ansj/issues/40)

**Comment by wpzdm** [comment]
那是否可以通过在全局配置中构造一个不分词的ansj来workaround，像这样：
$ES_HOME/config/elasticsearch.yml
```
index.analysis.analyzer.index_ansj_nonstop:
  type: index_ansj
  enabled_stop_filter: false
  ...
```

```
PUT /my_index
{
   "settings":{
      "analysis":{
         "analyzer":{
            "default":{
            	"type": "index_ansj_nonstop"
            }
         }
      }
   }
}
```
