### ISSUE TITLE
是否可以实现某字段使用停用词某字段不使用停用词?

### ISSUE THREAD

**Issue by bigfanofcpp** [NLPchina/elasticsearch-analysis-ansj#78]
如题,es自己的分词都是支持的,比如standard等等可以设置stopwords为none.

**Comment by shi-yuan** [comment]
可以，两个字段，分别用不同的分词器，一个设置了停用词，一个没有设置

**Comment by bigfanofcpp** [comment]
请问如何设置?给我个例子,谢谢!

**Comment by shi-yuan** [comment]
可以看看配置https://github.com/NLPchina/elasticsearch-analysis-ansj#242或520以上

**Comment by shi-yuan** [comment]
配置自定义分词器

**Comment by bigfanofcpp** [comment]
elasticsearch里面有个stopwords,来设置每个字段的停用词,我分词设置成ansj,并且设置了stopwords后,发现不管用.

**Comment by shi-yuan** [comment]
配置两个分词器：
```yml
index:
  analysis:
    tokenizer :
      stop :
        type : dic_ansj 
        stop: stop
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false
      nostop :
        type : dic_ansj 
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false

    analyzer:
      stop:
        type: custom
        tokenizer: stop
      nostop:
        type: custom
        tokenizer: nostop
```

mapping里分别配置不同的analyzer
