### ISSUE TITLE
v2.3.1 配置停用词典无效

### ISSUE THREAD

**Issue by buaanie** [NLPchina/elasticsearch-analysis-ansj#85]
log:

```
 not find library.properties in classpath use it by default !
 init user userLibrary ok path is : /usr/app/elasticsearch/config/ansj/dic/user/sougou.dic
 init ambiguityLibrary ok!
 init user userLibrary ok path is : /usr/app/elasticsearch-2.3.1/plugins/elasticsearch-analysis-ansj/default.dic
 ansj停止词典加载完毕!
 ansj分词器预热完毕，可以使用! 没有找到redis相关配置!
regedit analyzer named : index_ansj
 regedit analyzer named : query_ansj
```
配置：
```
ansj:
 dic_path: "dic/sougou.dic" 
 ##ambiguity_path: "ansj/dic/ambiguity.dic"
 enable_name_recognition: true
 enable_num_recognition: true 
 enable_quantifier_recognition: false 
 enabled_stop_filter: true 
 enable_skip_user_define: false 
 stop_path: "dic/stopLibrary.dic" 
```

按照[issue21](https://github.com/NLPchina/elasticsearch-analysis-ansj/issues/21) 的方法自己编译了一下，但是还是不能读取停用词
