### ISSUE TITLE
redis一直配置不成功

### ISSUE THREAD

**Issue by skybusy2000** [NLPchina/elasticsearch-analysis-ansj#89]
![image](https://user-images.githubusercontent.com/3365868/29870377-bea87066-8db9-11e7-926f-c2dac7de8332.png)
能帮我看看什么地方写错了么

**Comment by shi-yuan** [comment]
写的没问题啊，不成功？有日志信息吗？

**Comment by skybusy2000** [comment]
![image](https://user-images.githubusercontent.com/3365868/29913864-fd889d9c-8e68-11e7-9e7f-471b41dfdcd8.png)
本来开始以为是缩进的问题 改了空2格、换行符都不行。

**Comment by shi-yuan** [comment]
这是我的配置：
```yml
script.inline: true
script.indexed: true

index.analysis.analyzer.default.type: index_ansj
index.analysis.analyzer.default_search.type: query_ansj

threadpool:
  bulk:
    type: fixed
    size: 100
    queue_size: 1000
ansj:
  dic_path: "ansj/dic/user/"
  redis:
    pool:
      maxactive: 20
      maxidle: 10
      testonborrow: true
    ip: 192.168.10.9:6379
    timeout: 2000
    channel: ansj_term
```

没问题的
