### ISSUE TITLE
5.5.2配置了自定义词典和停用词都不生效

### ISSUE THREAD

**Issue by haochun** [NLPchina/elasticsearch-analysis-ansj#90]
# 全局变量配置方式一
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  dic: default.dic
  dic: file://D:/elasticsearch-5.5.2/plugins/elasticsearch-analysis-ansjuser/user/sougou.dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
  stop: file://D:/elasticsearch-5.5.2/plugins/elasticsearch-analysis-ansjuser/stopLibrary.dic
  # http方式加载
  #dic_d1: http://xxx/xx.dic
  # jar中文件加载
  #dic_d2: jar://org.ansj.dic.DicReader|/dic2.dic
  # 从数据库中加载
  #dic_d3: jdbc:mysql://xxxx:3306/ttt?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|username|password|select name as name,nature,freq from dic where type=1
  # 从自定义类中加载,YourClas  extends PathToStream
  #dic_d3: class://xxx.xxx.YourClas|ohterparam

  #过滤词典配置
  #stop: http,file,jar,class,jdbc 都支持
  #stop_key1: ...

  #歧义词典配置
  #ambiguity: http,file,jar,class,jdbc 都支持
  #ambiguity_key1: ...

  #同义词词典配置
  #synonyms: http,file,jar,class,jdbc 都支持
  #synonyms_key1: ...

# 全局变量配置方式二 通过配置文件的方式配置,优先级高于es本身的配置
#ansj_config: ansj_library.properties #http,file,jar,class,jdbc 都支持,格式参见ansj_library.properties

# 配置自定义分词器

index:
  analysis:
    tokenizer :
      my_dic :
        type : dic_ansj
        dic: dic
        stop: stop
        ambiguity: ambiguity
        synonyms: synonyms
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false

    analyzer:
      my_dic:
        type: custom
        tokenizer: my_dic

停用词和词库的数据不生效，并且 日志也没有任何加载的log

**Comment by shi-yuan** [comment]
请问ansj.cfg.yml是如何配置的呢？

**Comment by haochun** [comment]
上面就有呀

**Comment by shi-yuan** [comment]
上面的不是默认的内容吗？您没修改过？

**Comment by haochun** [comment]
您看一下顶部，用户自定义词典的位置

**Comment by shi-yuan** [comment]
这个？
```yml
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  dic: default.dic
  dic: file://D:/elasticsearch-5.5.2/plugins/elasticsearch-analysis-ansjuser/user/sougou.dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
  stop: file://D:/elasticsearch-5.5.2/plugins/elasticsearch-analysis-ansjuser/stopLibrary.dic
```

**Comment by shi-yuan** [comment]
我的ansj.cfg.yml配置：
```yml
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  # dic: default.dic
  # dic: file://D:/elasticsearch-5.5.2/plugins/elasticsearch-analysis-ansjuser/user/sougou.dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
  stop: E:/elasticsearch/elasticsearch-5.5.2/plugins/elasticsearch-ansj/dic/stop.dic
```

E:/elasticsearch/elasticsearch-5.5.2/plugins/elasticsearch-ansj/dic/stop.dic内容：
。
的

测试：http://localhost:9200/_analyze?analyzer=index_ansj&text=我爱我的祖国：
![qq 20170907213315](https://user-images.githubusercontent.com/8057153/30165870-32830586-9414-11e7-963a-5cd078012db5.png)

**Comment by haochun** [comment]
http://localhost:9200/_cat/ansj?text=%E6%88%91%E7%88%B1%E6%88%91%E7%9A%84%E7%A5%96%E5%9B%BD%E3%80%82&type=index_ansj&pretty
返回的json如下：
`
{
  "result" : [
    {
      "name" : "我",
      "nature" : "r",
      "offe" : 0,
      "realName" : "我",
      "synonyms" : null
    },
    {
      "name" : "爱",
      "nature" : "v",
      "offe" : 1,
      "realName" : "爱",
      "synonyms" : null
    },
    {
      "name" : "我",
      "nature" : "r",
      "offe" : 2,
      "realName" : "我",
      "synonyms" : null
    },
    {
      "name" : "的",
      "nature" : "uj",
      "offe" : 3,
      "realName" : "的",
      "synonyms" : null
    },
    {
      "name" : "祖国",
      "nature" : "n",
      "offe" : 4,
      "realName" : "祖国",
      "synonyms" : null
    },
    {
      "name" : "祖",
      "nature" : "ng",
      "offe" : 4,
      "realName" : "祖",
      "synonyms" : null
    },
    {
      "name" : "国",
      "nature" : "n",
      "offe" : 5,
      "realName" : "国",
      "synonyms" : null
    },
    {
      "name" : "。",
      "nature" : "w",
      "offe" : 6,
      "realName" : "。",
      "synonyms" : null
    }
  ]
}
`

**Comment by haochun** [comment]
![image](https://user-images.githubusercontent.com/9320176/30203118-967d2f72-94b3-11e7-8bd6-9a596ffe00e4.png)

我明明配置了，但log去这样 显示

**Comment by haochun** [comment]
我如果在elasticsearch-5.5.2/config下增加一个ansj_config.peroperties文件就是ok的，我感觉ansj.cfg.xml是不是没生效？或者windows的版本下有bug？

**Comment by shi-yuan** [comment]
访问_cat/ansj得带上词典：http://localhost:9200/_cat/ansj?text=我爱我的祖国。&type=index_ansj&stop=stop&pretty

访问_analyze，才会用全局默认的配置的：http://localhost:9200/_analyze?text=我爱我的祖国。&analyzer=index_ansj&pretty

**Comment by shi-yuan** [comment]
ansj.cfg.yml如果没有配置：
```yml
ansj:
  # 全局变量配置方式二 通过配置文件的方式配置,优先级高于es本身的配置
  ansj_config: ansj_library.properties
```
会去加载$ES_HOME/config/ansj_library.properties
